server:
  port: 9527
spring:
  application:
    name: gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route
          uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT-8012 #动态路由 利用微服务名称
#         uri: http://localhost:8012
          predicates:
            - Path=/payment/get/**
        - id: payment_route1
          uri: lb://CLOUD-PAYMENT-SERVICE #动态路由 利用微服务名称
            #         uri: http://localhost:8012
          predicates:
              - Path=/paymentService/getPaymentById/**
eureka:
  instance:
    hostname: cloud-gate-service
  client:
    service-url:
      register-with-eureka: true
      defaultZone: http://eureka9001.com:9001/eureka