server:
  port: 8015
spring:
  application:
    name: cloud-consumer-feign-hystrix-order8015
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #      #单机版
      defaultZone: http://eureka9001.com:9001/eureka
      # 集群版
  #      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka
  instance:
    instance-id: feign-order-8015
    #访问路径可以显示IP地址
    prefer-ip-address: true

ribbon:
  # 连接超时
  ConnectTimeout: 2000
  # 响应超时
  ReadTimeout: 3000
#开启hystrix
feign:
  hystrix:
    enabled: true